---

 - name: Create /var/www/public/vhost1 directory
   file:
    path: /var/www/public/vhost1
    state: directory

 - name: Create /var/www/public/vhost2 directory
   file:
    path: /var/www/public/vhost2
    state: directory

 - name: Copy template index.html file
   template: 
    src: /etc/ansible/Apache/Apache/templates/index.j2 
    dest: /var/www/public/vhost1/index.html

 - name: Copy template index.html file
   template:
    src: /etc/ansible/roles/Apache/templates/index2.j2
    dest: /var/www/public/vhost2/index.html

 - name: Create virtual host1
   template: 
    src: /etc/ansible/roles/Apache/templates/mon-site.j2 
    dest: /etc/apache2/sites-available/mon-site.conf

 - name: Activation of the host
   command: a2ensite mon-site

 - name: Create virtual host2
   template:
    src: /etc/ansible/roles/Apache/templates/mon-site2.j2
    dest: /etc/apache2/sites-available/mon-site2.conf

 - name: Activation of the host
   command: a2ensite mon-site2

 - name: desactivation of default host
   command: a2dissite 000-default
   notify:
    - Restart Apache2
